### ISSUE TITLE
Main Navigation: Add document collections to main navigation side bar 

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/townplanner#1]
Based on the townplan files provided in the domain directories add the collections as menu items to the side bar
They should be presented under each domain and use the colleciton name as their menu heading. 

This should always go to the index.html file in the dir/ listed in the townplan collection data

**Comment by roleyfoley** [comment]
@webilhan The menu looks how I expect it to and I've updated the dev data to confirm that the menu items are added and removed as required

Could you please expand the active accordion menu when a domain is selected? So that you can see what documentation is available for the domain

**Comment by webilhan** [comment]
@roleyfoley Made menu expanded on active state
