### ISSUE TITLE
Document Collection - Markdown: internal naviatgation

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/townplanner#3]
Within a mardown document collection I would like an additional navigation sidebar based on the navigation data provided in the townplan.json file for the domain. 

The pages listed in the townplan.json file should be relative to the document collection directory 

a home folder should always be at the top and point to the index.md file in the root of the document collection directory. 

All other navigation folders should be added to the menu in the order they are in the list

**Comment by webilhan** [comment]
@roleyfoley Added document and api collection to sidebar internal navigation
